version: '3.9'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack-pro:3.0.2   # required for Pro
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:443:443"
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # required for Docker support as per: https://docs.localstack.cloud/user-guide/aws/lambda/#troubleshooting
