name: Python and Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements_dev.txt
          yarn
      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[serverless]\naws_access_key_id = anyvalue\naws_secret_access_key = anyvalue\nregion = us-east-1" > ~/.aws/credentials
      - name: Deploy service
        env:
          LOG_LEVEL: "ERROR"
          DEBUG: "0"
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: yarn deploy
      - name: Run tests
        run: source venv/bin/activate && invoke alltests
      - name: Run linter
        run: source venv/bin/activate && PYTHONPATH=lambdas pylint ./lambdas